<?php

namespace backend\modules\adminx\controllers;

use common\models\UControl;
use yii\web\Controller;


class MainController extends Controller
{
    public $layout = '@app/modules/adminx/views/layouts/adminxLayout.php';

    /**
     * Ответ, который будет возвращаться на AJAX-запросы
     * @var array
     */
    public $result = [
        'status' => false,
        'data' => 'Інформацію не знайдено'
    ];

    public function beforeAction($action)
    {
        $r = 1;
        if (defined('YII_DEBUG') && YII_DEBUG) {
            \Yii::$app->getAssetManager()->forceCopy = true;
        }
        if (!\Yii::$app->request->isAjax){
            if (\Yii::$app->configs->userControl || \Yii::$app->configs->guestControl){
                $ret = UControl::guestsAndUsersControl();
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}