<?php

namespace common\controllers;

use backend\modules\adminx\models\UControl;
use yii\web\Controller;


class MainController extends Controller
{
    public $layout = '@app/common/views/layouts/commonLayout.php';
    /**
     * @var
     */
    public $accessData;

    /**
     * Ответ, который будет возвращаться на AJAX-запросы
     * @var array
     */
    public $result = [
        'status' => false,
        'data' => 'Інформацію не знайдено'
    ];

    public function beforeAction($action)
    {
        if (defined('YII_DEBUG') && YII_DEBUG) {
            \Yii::$app->getAssetManager()->forceCopy = true;
        }
        $r=1;

        if (!\Yii::$app->request->isAjax){
            if (\Yii::$app->configs->userControl || \Yii::$app->configs->guestControl){
                $ret = UControl::guestsAndUsersControl();
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}